Travis: run code-analysis only on Python 2.7.
On Python 3 I get:

$ bin/code-analysis
Flake8..........................[ FAILURE ] in 0.287s
/Users/maurits/shared-eggs/cp37m/pycodestyle-2.3.1-py3.7.egg/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp37m/flake8_coding-1.3.0-py3.7.egg/flake8_coding.py", line 55, in run
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/maurits/community/collective.denyroles/bin/flake8", line 33, in <module>
    sys.exit(flake8.main.cli.main())
  File "/Users/maurits/shared-eggs/cp37m/flake8-3.3.0-py3.7.egg/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/maurits/shared-eggs/cp37m/flake8-3.3.0-py3.7.egg/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/Users/maurits/shared-eggs/cp37m/flake8-3.3.0-py3.7.egg/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/Users/maurits/shared-eggs/cp37m/flake8-3.3.0-py3.7.egg/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/Users/maurits/shared-eggs/cp37m/flake8-3.3.0-py3.7.egg/flake8/checker.py", line 319, in run
    self.run_serial()
  File "/Users/maurits/shared-eggs/cp37m/flake8-3.3.0-py3.7.egg/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "/Users/maurits/shared-eggs/cp37m/flake8-3.3.0-py3.7.egg/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/Users/maurits/shared-eggs/cp37m/flake8-3.3.0-py3.7.egg/flake8/checker.py", line 487, in run_ast_checks
    for (line_number, offset, text, check) in runner:
RuntimeError: generator raised StopIteration